{% set name = "winflexbison" %}
{% set version = "2.5.25" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/lexxmark/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 8e1b71e037b524ba3f576babb0cf59182061df1f19cd86112f085a882560f60b
    patches:
      - fix-install.patch

build:
  number: 0
  skip: true  # [not win or vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
    - cmake

test:
  commands:
    - win_bison.exe --version
    - win_flex.exe --version

about:
  home: https://github.com/lexxmark/winflexbison
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - bison/src/COPYING
    - flex/src/COPYING
  summary: |
    WinFlexBison is a Windows port of Flex (the fast lexical analyser) and GNU Bison (parser generator).

extra:
  recipe-maintainers:
    - seanyen
    - js8544
